# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Gearman-Client-Async
version:      0.80
version_from: lib/Gearman/Client/Async.pm
installdirs:  site
requires:
    Danga::Socket:                 1.51
    Gearman::Client:               1.01
    Test::Simple:                  0.44

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
